export const texts = {
  ar: {
    marketingTeam: "التسويق",
    date: '',
    buildPlan: "بناء خطة تسويقية لعميل جديد",
    buildPlanDesc: "أنشئ خطة تسويقية شاملة تتضمن الأهداف والاستراتيجيات والجداول الزمنية",
    editPlan: "تعديل الخطة التسويقية لعميل",
    editPlanDesc: "قم بتحديث وتعديل الخطة التسويقية الحالية بناءً على النتائج والمستجدات",
    monthlyUpdate: "إعطاء مستجدات ملخص الشهر لعميل",
    monthlyUpdateDesc: "قدّم تقريراً شهرياً بالإنجازات والتحليلات والتوصيات للعميل",
    clients: "العملاء",
    clientCount: "عميل",
    clientName: "الوردة",
    clientType: "مطعم • خطة شهرية",
    progress: "التقدم",
    activeTasks: "مهام نشطة",
    lateTasks: "متأخرة",
    newMessages: "رسائل جديدة",
    clickToOpen: "اضغط للفتح",
    taskListTitle: "📝 قائمة المهام — الوردة",
    taskListHint: "قائمة المهام",
    newTask: "＋ مهمة جديدة",
    minimize: "تصغير",
    progressPlanMonth: "📈 تقدم خطة الشهر — مارس 2026",
    completed: "مكتملة",
    inProgress: "قيد التنفيذ",
    canceled: "ملغاة",
    totalProgress: "التقدم الكلي",
    deadlineAdherence: "الالتزام بالمواعيد",
    contentWeek1: "محتوى سوشيال",
    productShoot1: "تصوير منتجات",
    menuDesign: "تصميم قائمة الطعام",
    reelsVideo: "فيديو ريلز",
    ramadanCampaign: "حملة إعلانية",
    ramadanOffers: "تصميم عروض",
    kitchenReels: "فيديو ريلز — كواليس",
    contentWeek3: "محتوى سوشيال — أسبوع 3",
    teamChat: "💬 محادثة الفريق",
    remarkAssistant: "مساعد ريمارك",
    assistantMsg1: "صباح الخير! 👋 بناءً على تحليل الأداء الأسبوعي، أقترح التركيز على محتوى الفيديو هذا الأسبوع — معدل التفاعل كان أعلى بـ 3x مقارنة بالتصاميم.",
    marketingManager: "مدير التسويق",
    managerMsg: "ممتاز! خلينا نجهز 3 ريلز جديدة هالأسبوع. وديان، شو أخبار المحتوى اللي طلبه العميل؟",
    accountManager: "أكاونت منجر",
    accountManagerMsg: "العميل وافق على المحتوى الأسبوع الماضي ✅ بس عنده ملاحظة على الألوان في آخر تصميم.",
    assistantMsg2: "✨ تم تحديث مهمة \"تعديل ألوان التصميم\" تلقائياً. الموعد النهائي: بعد غد.",
    typeMsg: "اكتب رسالة...",
    calendarTitle: "تقويم المهام — مارس 2026",
    themeToggle: "الوضع الفاتح/الداكن",
    langToggle: "تغيير اللغة",
    addViewer: "إضافة مشاهدين",
    ceo: "المدير التنفيذي",
    coo: "المدير التشغيلي",
    designer: "مصمم جرافيك",
    // Wizard
    wizardTitle: "📋 بناء خطة تسويقية لعميل جديد",
    wizardStep1: "معلومات العميل",
    wizardStep2: "الأهداف والاستراتيجية",
    wizardStep3: "المحتوى والاجتماعات",
    wizardStep4: "المراجعة والإرسال",
    wClientName: "اسم العميل",
    wClientNamePH: "مثال: الوردة",
    wIndustry: "القطاع",
    wIndustryOpts: ["مطاعم ومقاهي", "عقارات", "تجارة إلكترونية", "صحة وجمال", "تعليم", "تقنية"],
    wPlanType: "نوع الخطة",
    wPlanTypeOpts: ["شهرية", "ربع سنوية", "سنوية", "حملة خاصة"],
    wBudget: "الميزانية الشهرية التقديرية",
    wBudgetPH: "مثال: 5,000 دولار",
    wGoals: "الأهداف التسويقية",
    wGoalsOpts: ["زيادة الوعي بالعلامة", "زيادة المبيعات", "زيادة المتابعين", "تحسين التفاعل", "إطلاق منتج جديد", "بناء الهوية البصرية"],
    wPlatforms: "المنصات المستهدفة",
    wPlatformOpts: ["Instagram", "TikTok", "Snapchat", "X (Twitter)", "Facebook", "LinkedIn", "YouTube", "Google Ads"],
    wTargetAudience: "الجمهور المستهدف",
    wTargetAudiencePH: "مثال: شباب 18-35 سنة في بغداد",
    wContentTypes: "أنواع المحتوى",
    wContentOpts: ["تصاميم سوشيال", "فيديو ريلز", "تصوير منتجات", "موشن جرافيك", "كتابة محتوى", "حملات إعلانية"],
    wPostsPerWeek: "عدد المنشورات أسبوعياً",
    wStartDate: "تاريخ البداية",
    wSocialLinks: "روابط صفحات التواصل الاجتماعي",
    wSocialLinkPH: "https://instagram.com/...",
    wAddLink: "＋ إضافة رابط",
    wUploadFiles: "رفع ملفات (اختياري)",
    wUploadHint: "اسحب الملفات هنا أو اضغط للاختيار",
    wMeetingBrief: "بريف الاجتماع الأولي",
    wMeetingBriefPH: "ملخص ما تم مناقشته في الاجتماع الأول مع العميل...",
    wNextMeeting: "موعد الاجتماع الثاني",
    wMeetingAttendees: "الحاضرون في الاجتماع",
    wTeamMembers: ["مصطفى خلف", "يوسف", "أحمد", "موسى", "حسنين", "وديان", "سيف", "عبدالله", "محمد"],
    wAddCustom: "＋ إضافة خيار آخر",
    wCustomPH: "اكتب خياراً جديداً...",
    wNotes: "ملاحظات إضافية",
    wNotesPH: "أي تفاصيل أخرى يريد مدير التسويق إضافتها...",
    wNext: "التالي ←",
    wPrev: "→ السابق",
    wSubmit: "✨ إرسال للمساعد الذكي",
    wClose: "إغلاق",
    wRequired: "مطلوب",
    wSelectPlaceholder: "اختر...",
    wAddPerson: "＋ إضافة شخص",
    wAddPersonPH: "اسم الشخص...",
    // Pipeline
    potentialClient: "🎯 عميل محتمل",
    pipelineStages: ["تواصل أولي", "اجتماع أول", "عرض سعر", "تفاوض", "اتفاق"],
    pipelineTitle: "مراحل التوصل لاتفاق",
    pNoClients: "لا يوجد عملاء محتملين حالياً",
    pScheduleMeeting: "📅 تحديد موعد اجتماع",
    pChangeStatus: "🔄 تغيير الحالة",
    pExportPlan: "📤 تصدير الخطة",
    pExportJSON: "📄 تصدير JSON",
    pExportPDF: "📃 تصدير PDF",
    pExportNotebook: "📓 إرسال إلى NotebookLM",
    pExportClipboard: "📎 نسخ للحافظة",
    pEditPlan: "✏️ تعديل الخطة",
    pAiChat: "🤖 حوار مع AI",
    pAddPerson: "👤 إضافة شخص",
    pMeetingDate: "تاريخ الاجتماع",
    pMeetingTime: "الوقت",
    pSelectAttendees: "اختر الحاضرين",
    // Stage-specific
    stageContactSource: "مصدر التواصل",
    stageContactSourceOpts: ["إحالة", "إعلان مدفوع", "سوشيال ميديا", "بحث مباشر", "معرفة سابقة"],
    stageInterestLevel: "مستوى الاهتمام",
    stageInterestOpts: ["مرتفع 🔥", "متوسط ⚡", "منخفض 💤"],
    stageContactNotes: "ملاحظات التواصل الأولي",
    stageContactNotesPH: "ماذا ناقشتم؟ ما الذي يبحث عنه العميل؟",
    stageMeetingBrief: "ملخص الاجتماع",
    stageMeetingBriefPH: "أهم النقاط التي تمت مناقشتها...",
    stageQuoteTitle: "💰 تفاصيل عرض السعر",
    stageQuoteAmount: "المبلغ المقترح",
    stageQuoteAmountPH: "مثلاً: 5,000 ر.س/شهرياً",
    stageQuoteServices: "الخدمات المشمولة",
    stageQuoteNotes: "ملاحظات العرض",
    stageQuoteNotesPH: "تفاصيل إضافية عن العرض...",
    stageSendQuote: "📨 إرسال العرض",
    stageNegTitle: "🤝 تفاصيل التفاوض",
    stageNegCounterOffer: "العرض المضاد من العميل",
    stageNegCounterOfferPH: "المبلغ أو التعديلات المطلوبة",
    stageNegOurResponse: "ردنا",
    stageNegOurResponsePH: "كيف نرد على العرض المضاد...",
    stageNegStatus: "حالة التفاوض",
    stageNegStatusOpts: ["بانتظار رد العميل", "بانتظار ردنا", "تم التوصل لاتفاق", "الغاء"],
    stageSaveNotes: "💾 حفظ",
    // Agreement stage
    wAgreementTitle: "📝 تفاصيل الاتفاق",
    wAgreedBudget: "الميزانية المتفق عليها",
    wAgreedBudgetPH: "المبلغ النهائي المتفق عليه",
    wAccountMgr: "الأكاونت منجر المسؤول",
    wAccountMgrOpts: ["وديان", "سيف"],
    wContractDuration: "مدة العقد",
    wContractOpts: ["شهر", "3 أشهر", "6 أشهر", "سنة"],
    wConfirmAgreement: "✅ تأكيد الاتفاق وتحويل لعميل",
    // Conversion
    conversionMsg: "🎉 مبروك! تم تحويل {name} إلى عميل رسمي.",
    calendarGenerated: "📅 تم إنشاء جدول المحتوى بناءً على الخطة التسويقية:",
    calWeek: "الأسبوع",
    calTask: "المهمة",
    calPlatform: "المنصة",
    sun: "أحد", mon: "إثن", tue: "ثلا", wed: "أربع", thu: "خمي", fri: "جمعة", sat: "سبت",
    // Edit Plan
    editPlanTitle: "✏️ تعديل الخطة التسويقية",
    selectClient: "اختر العميل",
    noClientsAvailable: "لا يوجد عملاء حالياً",
    saveChanges: "💾 حفظ التعديلات",
    // Monthly Summary
    summaryTitle: "📊 ملخص الشهر",
    summaryMonth: "الشهر",
    summaryMonths: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
    summaryYear: "السنة",
    summaryPostsPublished: "عدد المنشورات المنشورة",
    summaryEngagement: "إجمالي التفاعل (إعجابات، تعليقات، مشاركات)",
    summaryFollowersGained: "المتابعون الجدد",
    summaryBestPost: "أفضل منشور أداءً",
    summaryBestPostPH: "رابط أو وصف أفضل منشور...",
    summaryHighlights: "أبرز الإنجازات",
    summaryHighlightsPH: "ما هي أهم الإنجازات التي تحققت هذا الشهر؟",
    summaryChallenges: "التحديات",
    summaryChallengesPH: "ما هي أبرز التحديات التي واجهتكم؟",
    summaryRecommendations: "التوصيات للشهر القادم",
    summaryRecommendationsPH: "ما هي خطتكم وتوصياتكم للشهر القادم؟",
    summaryClientFeedback: "ملاحظات العميل",
    summaryClientFeedbackPH: "أي ملاحظات من العميل...",
    summarySubmit: "✨ إرسال الملخص",
    summarySuccess: "✅ تم حفظ ملخص {month} بنجاح لعميل {client}",
    editSuccess: "✅ تم تحديث الخطة التسويقية لعميل {client} بنجاح",
  },
  en: {
    marketingTeam: "Marketing",
    date: '',
    buildPlan: "Build marketing plan for a new client",
    buildPlanDesc: "Create a comprehensive marketing plan that includes goals, strategies, and timelines.",
    editPlan: "Modify a client's marketing plan",
    editPlanDesc: "Update and modify the current marketing plan based on results and new developments.",
    monthlyUpdate: "Provide a monthly summary update",
    monthlyUpdateDesc: "Provide the client with a monthly report detailing achievements, analyses, and recommendations.",
    clients: "Customers",
    clientCount: "client(s)",
    clientName: "The Rose",
    clientType: "Restaurant • Monthly Plan",
    progress: "Progress",
    activeTasks: "Active tasks",
    lateTasks: "Late",
    newMessages: "New messages",
    clickToOpen: "Click to open",
    taskListTitle: "📝 Task List — The Rose",
    taskListHint: "Task list",
    newTask: "＋ New mission",
    minimize: "Minimize",
    progressPlanMonth: "📈 Monthly Plan Progress — March 2026",
    completed: "Complete",
    inProgress: "In progress",
    canceled: "Cancelled",
    totalProgress: "Overall progress",
    deadlineAdherence: "Adherence to deadlines",
    contentWeek1: "Social content",
    productShoot1: "Product photography",
    menuDesign: "Menu design",
    reelsVideo: "Reels video",
    ramadanCampaign: "Ad campaign",
    ramadanOffers: "Offers design",
    kitchenReels: "Behind the scenes",
    teamChat: "💬 Team Chat",
    remarkAssistant: "Remark Assistant",
    assistantMsg1: "Good morning! 👋 Based on the weekly performance analysis, I suggest focusing on video content this week — the engagement rate was 3x higher compared to static designs.",
    marketingManager: "Marketing Manager",
    managerMsg: "Great! Let's get 3 new reels ready this week. Dian, what's the latest on the content requested?",
    accountManager: "Account Manager",
    accountManagerMsg: "The client approved the content last week ✅ but they had a comment on the colors in the latest design.",
    assistantMsg2: "✨ \"Adjust design colors\" task has been updated automatically. Deadline: The day after tomorrow.",
    typeMsg: "Type a message...",
    calendarTitle: "Task Calendar — March 2026",
    themeToggle: "Light/Dark Mode",
    langToggle: "Change language",
    addViewer: "Add Viewer",
    ceo: "CEO",
    coo: "COO",
    designer: "Graphic Designer",
    // Wizard
    wizardTitle: "📋 Build a Marketing Plan for a New Client",
    wizardStep1: "Client Info",
    wizardStep2: "Goals & Strategy",
    wizardStep3: "Content & Meetings",
    wizardStep4: "Review & Submit",
    wClientName: "Client Name",
    wClientNamePH: "e.g. The Rose",
    wIndustry: "Industry",
    wIndustryOpts: ["Restaurants & Cafés", "Real Estate", "E-commerce", "Health & Beauty", "Education", "Technology"],
    wPlanType: "Plan Type",
    wPlanTypeOpts: ["Monthly", "Quarterly", "Annual", "Special Campaign"],
    wBudget: "Estimated Monthly Budget",
    wBudgetPH: "e.g. $5,000",
    wGoals: "Marketing Goals",
    wGoalsOpts: ["Brand Awareness", "Increase Sales", "Grow Followers", "Improve Engagement", "Product Launch", "Visual Identity"],
    wPlatforms: "Target Platforms",
    wPlatformOpts: ["Instagram", "TikTok", "Snapchat", "X (Twitter)", "Facebook", "LinkedIn", "YouTube", "Google Ads"],
    wTargetAudience: "Target Audience",
    wTargetAudiencePH: "e.g. Youth 18-35 in Baghdad",
    wContentTypes: "Content Types",
    wContentOpts: ["Social Designs", "Reels Video", "Product Photography", "Motion Graphics", "Copywriting", "Ad Campaigns"],
    wPostsPerWeek: "Posts per Week",
    wStartDate: "Start Date",
    wSocialLinks: "Social Media Links",
    wSocialLinkPH: "https://instagram.com/...",
    wAddLink: "＋ Add Link",
    wUploadFiles: "Upload Files (Optional)",
    wUploadHint: "Drag files here or click to browse",
    wMeetingBrief: "Initial Meeting Brief",
    wMeetingBriefPH: "Summary of what was discussed in the first meeting with the client...",
    wNextMeeting: "Next Meeting Date",
    wMeetingAttendees: "Meeting Attendees",
    wTeamMembers: ["Mustafa Khalaf", "Yousif", "Ahmed", "Musa", "Hassanin", "Wedyan", "Saif", "Abdullah", "Mohammed"],
    wAddCustom: "＋ Add Custom Option",
    wCustomPH: "Type a new option...",
    wNotes: "Additional Notes",
    wNotesPH: "Any other details the marketing manager wants to add...",
    wNext: "Next →",
    wPrev: "← Previous",
    wSubmit: "✨ Send to AI Assistant",
    wClose: "Close",
    wRequired: "Required",
    wSelectPlaceholder: "Select...",
    wAddPerson: "＋ Add Person",
    wAddPersonPH: "Person name...",
    // Pipeline
    potentialClient: "🎯 Potential Client",
    pipelineStages: ["Initial Contact", "First Meeting", "Proposal", "Negotiation", "Agreement"],
    pipelineTitle: "Deal Pipeline",
    pNoClients: "No potential clients at the moment",
    pScheduleMeeting: "📅 Schedule Meeting",
    pChangeStatus: "🔄 Change Status",
    pExportPlan: "📤 Export Plan",
    pExportJSON: "📄 Export JSON",
    pExportPDF: "📃 Export PDF",
    pExportNotebook: "📓 Send to NotebookLM",
    pExportClipboard: "📎 Copy to Clipboard",
    pEditPlan: "✏️ Edit Plan",
    pAiChat: "🤖 AI Chat",
    pAddPerson: "👤 Add Person",
    pMeetingDate: "Meeting Date",
    pMeetingTime: "Time",
    pSelectAttendees: "Select Attendees",
    // Stage-specific
    stageContactSource: "Contact Source",
    stageContactSourceOpts: ["Referral", "Paid Ad", "Social Media", "Direct Search", "Previous Connection"],
    stageInterestLevel: "Interest Level",
    stageInterestOpts: ["High 🔥", "Medium ⚡", "Low 💤"],
    stageContactNotes: "Initial Contact Notes",
    stageContactNotesPH: "What did you discuss? What is the client looking for?",
    stageMeetingBrief: "Meeting Brief",
    stageMeetingBriefPH: "Key points discussed...",
    stageQuoteTitle: "💰 Quotation Details",
    stageQuoteAmount: "Proposed Amount",
    stageQuoteAmountPH: "e.g. $5,000/month",
    stageQuoteServices: "Included Services",
    stageQuoteNotes: "Quote Notes",
    stageQuoteNotesPH: "Additional details about the quote...",
    stageSendQuote: "📨 Send Quote",
    stageNegTitle: "🤝 Negotiation Details",
    stageNegCounterOffer: "Client Counter-Offer",
    stageNegCounterOfferPH: "Amount or requested adjustments",
    stageNegOurResponse: "Our Response",
    stageNegOurResponsePH: "How we respond to the counter-offer...",
    stageNegStatus: "Negotiation Status",
    stageNegStatusOpts: ["Awaiting Client", "Awaiting Us", "Agreement Reached", "Cancelled"],
    stageSaveNotes: "💾 Save",
    // Agreement stage
    wAgreementTitle: "📝 Agreement Details",
    wAgreedBudget: "Agreed Budget",
    wAgreedBudgetPH: "Final agreed amount",
    wAccountMgr: "Assigned Account Manager",
    wAccountMgrOpts: ["Wedyan", "Saif"],
    wContractDuration: "Contract Duration",
    wContractOpts: ["1 Month", "3 Months", "6 Months", "1 Year"],
    wConfirmAgreement: "✅ Confirm & Convert to Client",
    // Conversion
    conversionMsg: "🎉 Congrats! {name} has been converted to an official client.",
    calendarGenerated: "📅 Content calendar generated from the marketing plan:",
    calWeek: "Week",
    calTask: "Task",
    calPlatform: "Platform",
    contentWeek3: "Social content - Week 3",
    sun: "Sun", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat",
    // Edit Plan
    editPlanTitle: "✏️ Edit Marketing Plan",
    selectClient: "Select Client",
    noClientsAvailable: "No clients available",
    saveChanges: "💾 Save Changes",
    // Monthly Summary
    summaryTitle: "📊 Monthly Summary",
    summaryMonth: "Month",
    summaryMonths: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    summaryYear: "Year",
    summaryPostsPublished: "Posts Published",
    summaryEngagement: "Total Engagement (likes, comments, shares)",
    summaryFollowersGained: "Followers Gained",
    summaryBestPost: "Best Performing Post",
    summaryBestPostPH: "Link or description of best post...",
    summaryHighlights: "Key Highlights",
    summaryHighlightsPH: "What were the key achievements this month?",
    summaryChallenges: "Challenges",
    summaryChallengesPH: "What challenges did you face?",
    summaryRecommendations: "Recommendations for Next Month",
    summaryRecommendationsPH: "What are your plans and recommendations for next month?",
    summaryClientFeedback: "Client Feedback",
    summaryClientFeedbackPH: "Any feedback from the client...",
    summarySubmit: "✨ Submit Summary",
    summarySuccess: "✅ {month} summary saved successfully for {client}",
    editSuccess: "✅ Marketing plan updated successfully for {client}",
  }
};
